In [11]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GroupKFold, GridSearchCV, cross_val_predict
from sklearn.metrics import accuracy_score, confusion_matrix

In [2]:
training_data = np.load('C://Users//krist//Desktop//ITU//3_semester//machine_learning//MLProject2024//MLProject2024//fashion_train.npy')
test_data = np.load('C://Users//krist//Desktop//ITU//3_semester//machine_learning//MLProject2024//MLProject2024//fashion_test.npy')

In [3]:
df_train = pd.DataFrame(training_data)
df_test = pd.DataFrame(test_data)

In [4]:
X_train = df_train.iloc[:, :-1]  # All columns except the last one are features
y_train = df_train.iloc[:, -1]   # The last column is the label

X_test = df_test.iloc[:, :-1]  # All columns except the last one are features
y_test = df_test.iloc[:, -1]   # The last column is the label

In [32]:
# Define the parameter grid for grid search
param_grid = {
    'max_depth': [10,15,20,25,30,40,50,60,70,80],  # Maximum depth of the tree
    'min_samples_split': [2, 5, 10],   # Minimum number of samples required to split an internal node
    'min_samples_leaf': [1, 2, 4]      # Minimum number of samples required to be at a leaf node
}


clf_Tree = DecisionTreeClassifier(random_state=42)

group_kfold = GroupKFold(n_splits=5)


# Assuming X_train is a DataFrame or Series
groups_train = (X_train.index // 100)

# Initialize GridSearchCV with the GroupKFold
grid_search = GridSearchCV(clf_Tree, param_grid, cv=group_kfold, n_jobs=-1, scoring='accuracy')
# Perform grid search cross-validation 
grid_search.fit(X_train, y_train, groups=groups_train)

# Get the best model
best_decision_tree = grid_search.best_estimator_

y_pred_best = best_decision_tree.predict(X_test)

KeyboardInterrupt: 

In [6]:
# Evaluate the best model
accuracy_best = accuracy_score(y_test, y_pred_best)
print("Best Decision Tree Accuracy:", accuracy_best)

# Compute confusion matrix for the best model
cm_best = confusion_matrix(y_test, y_pred_best)
print("Best Model Confusion Matrix:")
print(cm_best)

Best Decision Tree Accuracy: 0.7682
Best Model Confusion Matrix:
[[740   7  21  55 177]
 [ 15 933   5  33  14]
 [ 27   4 754  22 193]
 [ 48  31  19 825  77]
 [167  12 172  60 589]]


In [26]:
clf_MLP = MLPClassifier(random_state=42)
clf_MLP.fit(X_train, y_train);

In [10]:
# Make predictions on the test set
y_pred_best = clf_MLP.predict(X_test)

# Evaluate the best model
accuracy_best = accuracy_score(y_test, y_pred_best)
print("Best Decision Tree Accuracy:", accuracy_best)

# Compute confusion matrix for the best model
cm_best = confusion_matrix(y_test, y_pred_best)
print("Best Model Confusion Matrix:")
print(cm_best)

Best Decision Tree Accuracy: 0.8216
Best Model Confusion Matrix:
[[822   3  46  32  97]
 [  5 949   6  32   8]
 [ 13   1 830  18 138]
 [ 41  14  31 862  52]
 [175   3 143  34 645]]


In [27]:
clf_Knn = KNeighborsClassifier(n_neighbors=10)
clf_Knn.fit(X_train, y_train);

In [24]:
# Make predictions on the test set
y_pred_best = clf_Knn.predict(X_test)

# Evaluate the best model
accuracy_best = accuracy_score(y_test, y_pred_best)
print("Best Decision Tree Accuracy:", accuracy_best)

# Compute confusion matrix for the best model
cm_best = confusion_matrix(y_test, y_pred_best)
print("Best Model Confusion Matrix:")
print(cm_best)

Best Decision Tree Accuracy: 0.825
Best Model Confusion Matrix:
[[857   2  25  22  94]
 [ 11 950  12  21   6]
 [ 15   1 866  14 104]
 [ 50   5  19 882  44]
 [203   0 194  33 570]]
